config/routes.rb
Rails.application.routes.draw do
  resources :carts do
    collection do
      get :owners
    end
  end
  resources :cart_items
  post "/carts/new", to: "carts#new"
  resources :products
  root to: "carts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  validates :owner, presence: true, uniqueness: true
  accepts_nested_attributes_for :cart_items, allow_destroy: true

  def total
    cart_items.map(&:price).sum.to_money
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    if params[:picked_up].present?
      @carts = @carts.includes(:cart_items).where(
        cart_items: { picked_up: params[:picked_up] }
      )
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    cart = Cart.find_or_create_by!(owner: cart_params[:owner])
    redirect_to edit_cart_path(cart)
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def owners
    owners = Cart.where("UPPER(owner) LIKE UPPER(?)", "%#{params[:query]}%").map(&:owner)
    render json: {
      suggestions: owners.map { |o| { value: o, data: o } }
    }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(
        :owner,
        cart_items_attributes: [:id, :quantity, :picked_up, :_destroy]
      )
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= f.text_field :owner, class: "mdl-textfield__input" %> <%= f.label :owner, "Dono", class: "mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= search_field_tag "product", "", class: "mdl-textfield__input" %>
    <%= label_tag "product", "Adicionar produto ao carrinho", class: "mdl-textfield__label" %>
  </div>

  <a class="mdl-button" id="add-product">Criar e adicionar produto</a>

  <%= render "cart_items/cart_items", cart_items: cart.cart_items, f: f %>

  <div>
    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="cash">
      <input id="cash" class="mdl-radio__button" type="radio" name="paymentMethod" value="cash" checked>
      <span class="mdl-radio__label">Dinheiro</span>
    </label>

    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="debit-card">
      <input id="debit-card" class="mdl-radio__button" type="radio" name="paymentMethod" value="debitCard">
      <span class="mdl-radio__label">Débito</span>
    </label>

    <label class="mdl-radio mdl-js-radio mdl-js-ripple-effect" for="credit-card">
      <input id="credit-card" class="mdl-radio__button" type="radio" name="paymentMethod" value="creditCard">
      <span class="mdl-radio__label">Crédito</span>
    </label>

    <div class="credit-card-provider">
      <label>
        <input type="radio" name="provider" value="payleven" checked>
        Payleven
      </label>

      <label>
        <input type="radio" name="provider" value="picpay">
        PicPay
      </label>
    </div>

    <div class="installments">
      <label for="installments">Parcelas:</label>
      <select id="installments">
        <option value="0">1x</option>
        <option value="1">2x</option>
        <option value="2">3x</option>
        <option value="3">4x</option>
        <option value="4">5x</option>
        <option value="5">6x</option>
        <option value="6">7x</option>
        <option value="7">8x</option>
        <option value="8">9x</option>
        <option value="9">10x</option>
        <option value="10">11x</option>
        <option value="11">12x</option>
      </select>
    </div>
  </div>

  <div class="actions">
    <%= f.submit class: "mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect mdl-button--primary" %>
  </div>
<% end %>

<dialog class="mdl-dialog" id="create-product-dialog">
  <%= render 'products/form', product: Product.new %>
</dialog>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<%= form_tag new_cart_path do %>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <input class="mdl-textfield__input" type="text" name="cart[owner]" id="cart-owner">
    <label class="mdl-textfield__label" for="cart-owner">Dono</label>
  </div>
<% end %>

<%= form_tag carts_path, method: :get do %>
  <select name="picked_up">
    <option value="true">Tem items já levados</option>
    <option value="false">Tem items não levados</option>
    <option value="">Indiferente</option>
  </select>

  <button class="mdl-button">Filtrar</button>
<% end %>

<table class="mdl-data-table">
  <thead>
    <tr>
      <th>Dono</th>
      <th>Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= cart.owner %></td>
        <td><%= cart.total.format %></td>
        <td><%= link_to 'Show', cart, class: "mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect" %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart), class: "mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect" %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' }, class: "mdl-button mdl-button--raised mdl-js-button mdl-js-ripple-effect mdl-button--accent" %></td>
      </tr>
    <% end %>

    <tr>
      <td>Total:</td>
      <td><%= @carts.map(&:total).sum.to_money.format %></td>
      <td colspan="3"></td>
    </tr>
  </tbody>
</table>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Owner:</strong>
  <%= @cart.owner %>
</p>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>