config/routes.rb
Rails.application.routes.draw do
  resources :carts do
    collection do
      get :owners
    end
  end
  resources :cart_items
  post "/carts/new", to: "carts#new"
  resources :products
  root to: "carts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  default_scope { order(created_at: :desc) }

  validate :has_stock

  def price
    product.price * quantity
  end

  private

    def has_stock
      before, after = changes[:quantity]
      difference = if before
                     after - before
                   elsif after
                     quantity
                   else
                     0
                   end
      if product.remaining - difference < 0
        errors.add(:quantity, "Não há quantidade o suficiente para #{product.name}")
      end
    end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items
  # POST /cart_items.json
  def create
    if @cart_item = CartItem.find_by(cart_id: cart_item_params[:cart_id], product_id: cart_item_params[:product_id])
      @cart_item.quantity += cart_item_params[:quantity] || 1
    else
      @cart_item = CartItem.new(cart_item_params)
    end

    if @cart_item.save
      form = nil
      view_context.form_for(@cart_item.cart) { |f| form = f }

      render json: {
        html: render_to_string(
          "_cart_items",
          layout: false,
          locals: {
            cart_items: @cart_item.cart.cart_items,
            f: form
          }
        )
      }
    else
      render json: @cart_item.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: 'Cart item was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:cart_id, :product_id, :quantity)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_cart_item_row.html.erb
<tr>
  <td><%= cart_item.product.name %></td>
  <td data-product-price-cents="<%= cart_item.product.price_cents %>"><%= cart_item.product.price.format %></td>
  <td>
    <% total = cart_item.product.remaining + cart_item.quantity %>
    <%= f.number_field :quantity, min: 1, max: total, class: "quantity" %> / <%= total %>
  </td>
  <td><%= f.check_box :picked_up %></td>
  <td class="cart-item-price"><%= cart_item.price.format %></td>
  <td>
    <%= f.hidden_field :_destroy, class: "destroy" %>
    <a class="destroy-cart-item mdl-button mdl-js-button mdl-button--icon mdl-button--colored mdl-button--accent">
      <i class="material-icons">close</i>
    </a>
  </td>
</tr>

app/views/cart_items/_cart_items.html.erb
<table id="cart-items" class="mdl-data-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Individual price</th>
      <th>Quantity</th>
      <th>Picked up</th>
      <th>Final price</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <%= f.fields_for(:cart_items) do |builder| %>
      <%= render "cart_items/cart_item_row", cart_item: builder.object, f: builder %>
    <% end %>

    <tr>
      <td colspan="3" style="text-align: right;">Total:</td>
      <td class="cart-total"><%= f.object.total.format %></td>
      <td></td>
    </tr>
  </tbody>
</table>

app/views/cart_items/_form.html.erb
<%= form_for(cart_item) do |f| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
      <% cart_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>